### ISSUE TITLE
API broken?

### ISSUE THREAD

**Issue by dcolley** [Colm3na/polkastats-ng#25]
API broken?

I use Brave browser and Pi-Hole.

https://kusama.polkastats.io/validator/HyLisujX7Cr6D7xzb6qadFdedLt8hmArB6ZVGJ6xsCUHqmx

![image](https://user-images.githubusercontent.com/1845970/172152995-ab00137b-218a-47b5-9508-af5a66a7c4b7.png)

**Comment by mariopino** [comment]
Hi @dcolley, thanks for reporting, it's fixed now!
