### ISSUE TITLE
Running for other chain Substrate

### ISSUE THREAD

**Issue by duythien** [Colm3na/polkastats-ng#4]
Hello

My project build on Substrate, and when I try to setup this project on localhost it working well for Kusama and Polkadot, but when I try to test for own blockchain https://node.phuquoc.dog get the error below

<img width="708" alt="Screen Shot 2021-09-02 at 17 46 10" src="https://user-images.githubusercontent.com/1762691/131830585-3b30097f-f17a-48da-96dd-9aa80717b55f.png">

![image](https://user-images.githubusercontent.com/1762691/131831740-9e941438-a8f3-4b58-a468-17c3b0efcb08.png)

The config frontend

```
export const network = {
  id: 'phuquocdog',
  name: 'Phu Quoc Dog',
  tokenSymbol: 'PQD',
  tokenDecimals: 10,
  ss58Format: 42,
  coinGeckoDenom: 'phuquocdog',
  nodeWs: 'wss://node.phuquoc.dog',
  backendWs: 'ws://localhost:8082/v1/graphql',
  backendHttp: 'http://localhost:8082/v1/graphql',
  googleAnalytics: 'UA-172854168-1',
  theme: '@/assets/scss/themes/polkastats.scss',
  // ranking
  historySize: 84, // 21 days
  erasPerDay: 4,
  validatorSetSize: 24,
}
export const paginationOptions = [10, 20, 50, 100]
```
Thanks

**Comment by karthiknvlr** [comment]
Make sure you have provided public access to the tables in Hasura. For more info refer to [this](https://hasura.io/docs/latest/graphql/core/auth/authorization/common-roles-auth-examples.html#anonymous-not-logged-in-users).

**Comment by duythien** [comment]
@karthiknvlr it work for now thanks

**Comment by x20ab** [comment]
hello @karthiknvlr ... I'm having some issues using substrate project, I have no validator and no staking yet.
The crawler is logging ==> 
{"level":50,"time":1641917628145,"pid":36,"hostname":"e3f3ac9ff4f9","crawler":"blockListener","msg":"Error adding block #1426007: TypeError: Cannot read property 'activeEra' of undefined\n    at /usr/app/crawler/crawlers/blockListener.js:62:27\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"} 
Any idea ?
Thanks
